CREATE DATABASE IF NOT EXISTS [[MARIADB_DATABASE]];
CREATE USER IF NOT EXISTS '[[MARIADB_USER]]'@'localhost' IDENTIFIED BY '[[MARIADB_PASSWORD]]';
GRANT ALL PRIVILEGES ON [[MARIADB_DATABASE]].* TO '[[MARIADB_USER]]'@'localhost';
FLUSH PRIVILEGES;
